# fly.toml app configuration file generated for lineastr-keeper on 2026-05-04T02:03:39+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lineastr-keeper'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'immediate'

[env]
  BUY_THRESHOLD_WEI = '1000000000000000'
  CHAIN_NAME = 'base-sepolia'
  CRON_SCHEDULE = '*/30 * * * *'

[[restart]]
  policy = 'always'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
